language: python
cache:
  - pip
python:
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_image_testing
  - KOTTI_TEST_DB_STRING=mysql://root@localhost:3306/kotti_image_testing
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - pip install -U pip
  - pip install psycopg2 mysqlclient
  - pip install -e . Kotti<2.0.0.dev0
  - pip install "wsgi_intercept==0.5.1"
  - python setup.py dev
before_script:
  - psql -c 'create database kotti_image_testing;' -U postgres
  - mysql -e 'create database kotti_image_testing;'
script: py.test --tb=native --cov=kotti_image --cov-report=term-missing
